name: My First workflow
on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo
          uses: actions/checkout@v7
        - name: Welcome messgae
          run: echo "my first action"
        - name: List files
          run: ls

        - name: Read files
          run: cat README.md
        